issuer: https://token.actions.githubusercontent.com
subject_pattern: repo:shopware/conflicts:refs/heads/main
claim_pattern:
  job_workflow_ref: shopware/conflicts/.github/workflows/update-usage-docs.yml@refs/heads/main

permissions:
  contents: write