name: Update Composer Tags

on:
  push:
    branches:
      - main
    paths:
      - composer.*.json
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-tags:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Git config
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Update tags
        run: bash .github/retag_on_composer_change.sh

      - name: Push updated tags
        run: bash .github/push_updated_tags.sh
